version: '3.9'
frontend:
    build: 
      context: frontend-node/
      dockerfile: Dockerfile
    init: true
    environment:
      BACKEND_URL: backend:8080
    deploy:
      replicas: 1
    networks:
    - application
    ports:
    - "9091:8080"
    depends_on:
    - backend
networks:
  application:
    name: application

